DoAnWeb/Models/Position.cs
using System.ComponentModel.DataAnnotations;

namespace DoAnWeb.Models
{
    public class Position
    {
        [Key]
        public int positionId { get; set; }
        [MaxLength(50)]
        public required string positionName { get; set; }
        public string? positionDescription { get; set; }
        [Required]
        public decimal positionSalary { get; set; }
        public required ICollection<Employee> employees { get; set; }
    }
}

DoAnWeb/Controllers/PositionController.cs
using DoAnWeb.Data;
using DoAnWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DoAnWeb.Controllers
{
    [Authorize(Roles = SD.Role_Admin)]
    public class PositionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PositionController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Position> positions = _context.positions.ToList();
            return View(positions);
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(Position position)
        {
            if (position.positionSalary != null && position.positionName != null)
            {
                _context.positions.Add(position);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(position);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var position = await _context.positions.FindAsync(id);
            try
            {
                _context.positions.Remove(position);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                // Xử lý lỗi và hiển thị thông báo cho người dùng
                ModelState.AddModelError("", $"Error deleting position: {ex.Message}");
                return View(position);
            }
        }
        public async Task<IActionResult> Update(int id)
        {


            var position = await _context.positions.FindAsync(id);
            if (position == null)
            {
                return NotFound();
            }

            return View(position);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id,  Position position)
        {
            if (id != position.positionId)
            {
                return NotFound();
            }
            if (position.positionName != null && position.positionSalary != null )
            {
                try
                {
                    var existingPosition = await _context.positions.FindAsync(id);
                    existingPosition.positionName = position.positionName;
                    existingPosition.positionDescription = position.positionDescription;
                    existingPosition.positionSalary = position.positionSalary;
                    _context.Update(existingPosition);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    // Xử lý khi xảy ra lỗi cập nhật
                    return NotFound();
                }
            }
            return View(position);
        }

        private bool PositionExists(int id)
        {
            return _context.positions.Any(e => e.positionId == id);
        }
    }
}

DoAnWeb/Views/Position/Add.cshtml
@model DoAnWeb.Models.Position
@* @section CustomStyles {
    <link rel="stylesheet" href="~/css/header1.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

} *@
@{
    ViewData["Title"] = "Add Position";
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
}
<style>
    .container {
        width: 80%;
        border: 1px solid black;
        border-radius: 20px;
        padding: 1.5rem;
        box-shadow: 0 0 10px rgba(0, 10, 0, 0.1);
        margin-left: auto;
        margin-right: auto;
    }

    .card {
        width: 80%;
        margin: auto;
    }
</style>
<div class="container">
    <div class="card">

        <div class="card-header">
            <h2 class="mb-0">Add Position</h2>
        </div>
        <div class="card-body">
            <form asp-action="Add" method="post" class="needs-validation" novalidate>
                <div class="form-group">
                    <label for="positionName">Position Name</label>
                    <input type="text" asp-for="positionName" class="form-control" id="positionName" required>
                    <span asp-validation-for="positionName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label for="positionDescription">Description</label>
                    <textarea asp-for="positionDescription" class="form-control" id="positionDescription"></textarea>
                </div>
                <div class="form-group">
                    <label asp-for="positionSalary" class="control-label">Salary</label>
                    <input asp-for="positionSalary" class="form-control" />
                    <span asp-validation-for="positionSalary" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary btn-block">Add</button>
            </form>
        </div>

    </div>
</div>

DoAnWeb/Views/Position/Index.cshtml
@model List<Position>
@{
    ViewData["Title"] = "Positions";
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
}
@* @section CustomStyles {
    <link rel="stylesheet" href="~/css/header1.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

} *@
<div class="container mt-4">
    <h2 class="text-center">Positions</h2>
    <div class="row mb-3">
        <div class="col-md-6">
            <a asp-action="Add" class="add-button">Create New</a>
        </div>
        <div class="col-md-6">
            <form id="searchForm" class="src">
                <i class="bx bx-search"></i>
                <input type="text" id="searchTerm" placeholder="Search...">
            </form>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Position Name</th>
                    <th scope="col">Description</th>
                    <th scope="col">Salary</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var position in Model)
                {
                    <tr>
                        <td>@position.positionName</td>
                        <td>@position.positionDescription</td>
                        <td>@position.positionSalary</td>
                        <td>
                            <div class="btn-group" role="group" aria-label="Position Actions">
                                <a asp-action="Update" asp-controller="Position" asp-route-id="@position.positionId">
                                    <button class="btn btn-primary btn-sm ">Update</button>
                                </a>
                                <form asp-action="Delete" asp-controller="Position" method="post" onsubmit="return confirm('Are you sure you want to delete this position?');">
                                    <input type="hidden" name="id" value="@position.positionId" />
                                    <button type="submit" class=" btn btn-sm btn-danger">Delete</button>
                                </form>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>


<style>
    .btn-group {
        display: flex;
        gap: 20px;
    }

    .container {
        border-radius: 20px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        padding: 20px;
        margin-top: 20px;
        background-color: #f9f9f9;
    }

    .src {
        position: relative;
        left: 200px;
        height: 40px;
        width: 350px;
        margin: 0 0 20px 0;
    }

        .src input {
            position: absolute;
            left: 0;
            top: 0;
            height: 100%;
            width: calc(100% - 50px);
            outline: none;
            border: none;
            background: #f8f3;
            padding-left: 50px;
            font-size: 15px;
            color: #000000;
            border-radius: 20px;
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
            transition: all 0.5s ease;
        }

        .src .bx {
            line-height: 1.8;
        }


        .src i {
            height: 50px;
            min-width: 50px;
            text-align: center;
            border-radius: 12px;
            font-size: 25px;
        }



    .add-button {
        background-color: #007bff;
        display: flex;
        align-items: center;
        justify-content: center;
        width: 150px;
        height: 40px;
        color: #fff;
        border: none;
        border-radius: 10px;
        padding: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

        .add-button:hover {
            background-color: #0056b3;
        }

    .table-responsive {
        overflow-x: auto;
    }

    th {
        background-color: #007bff;
        color: #fff;
        font-weight: bold;
        padding: 10px;
        text-align: left;
    }

    td {
        border: 1px solid #dee2e6;
        padding: 10px;
    }

    .table {
        width: 100%;
        border-collapse: collapse;
        border-spacing: 0;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }
</style>

<script>
    const searchTermInput = document.getElementById('searchTerm');
    searchTermInput.addEventListener('input', function () {
        const searchTerm = searchTermInput.value.trim();
        const tableRows = document.querySelectorAll('.table-striped tbody tr');
        tableRows.forEach(function (row) {
            const rowData = row.textContent || row.innerText;
            if (rowData.toUpperCase().indexOf(searchTerm.toUpperCase()) > -1) {
                row.style.display = '';
            } else {
                row.style.display = 'none';
            }
        });
    });
</script>

DoAnWeb/Views/Position/Update.cshtml
@model DoAnWeb.Models.Position
@* @section CustomStyles {
    <link rel="stylesheet" href="~/css/header1.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
} *@
@{
    ViewData["Title"] = "Edit Position";
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
}
<style>
    .container {
        width: 80%;
        border: 1px solid black;
        border-radius: 20px;
        padding: 1.5rem;
        box-shadow: 0 0 10px rgba(0, 10, 0, 0.1);
        margin-left: auto;
        margin-right: auto;
    }

    .card {
        width: 80%;
        margin: auto;
    }
</style>
<div class="container">
    <div class="card">
        <h2>Edit Position</h2>

        <form asp-action="Update" method="post">
            <input type="hidden" asp-for="positionId" />
            <div class="form-group">
                <label asp-for="positionName" class="control-label">Position Name</label>
                <input asp-for="positionName" class="form-control" />
                <span asp-validation-for="positionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="positionDescription" class="control-label">Description</label>
                <input asp-for="positionDescription" class="form-control" />
                <span asp-validation-for="positionDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="positionSalary" class="control-label">Salary</label>
                <input asp-for="positionSalary" class="form-control" />
                <span asp-validation-for="positionSalary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
</div>