DoAnWeb/Controllers/LawyerController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoAnWeb.Data;
using DoAnWeb.Models;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;
using iText.IO.Image;
using System.Net.Http;
using System.Net;
using Microsoft.AspNetCore.Authorization;

namespace DoAnWeb.Controllers
{
    [Authorize(Roles = SD.Role_Admin)]
    public class LawyerController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public LawyerController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // Action để hiển thị danh sách luật sư
        public IActionResult Index()
        {
            List<Employee> lawyers = _context.employees.ToList();
            return View(lawyers);
        }

        // Action để hiển thị thông tin cá nhân của luật sư
        public async Task<IActionResult> UserProfile(Employee employee)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            employee.employeeId = currentUser.employeeId;
            var employeeInfo = await _context.employees.FindAsync(employee.employeeId);
            if (employeeInfo == null)
            {
                return NotFound();
            }
            return View("UserProfile", employeeInfo);
        }

        // Action để thêm một luật sư mới
        public async Task<IActionResult> Add()
        {
            //Hiển listPosition
            var positions = await _context.positions.ToListAsync();
            var positionItems = positions.Select(p => new SelectListItem
            {
                Value = p.positionId.ToString(),
                Text = p.positionName
            }).ToList();

            ViewBag.Positions = positionItems;

            //Hiển listCategory
            var categories = await _context.categories.ToListAsync();
            var categoryItems = categories.Select(c => new SelectListItem
            {
                Value = c.categoryId.ToString(),
                Text = c.name
            }).ToList();

            ViewBag.Categories = categoryItems;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(Employee employee, IFormFile image)
        {
            if (employee.Address != null && employee.PhoneNumber != null && employee.FullName != null && employee.Expertise != null && employee.Email != null)
            {
                // Lấy thông tin vị trí từ cơ sở dữ liệu dựa trên positionId được gửi từ form
                employee.positions = await _context.positions.FindAsync(employee.positionId);

                // Lấy thông tin danh mục từ cơ sở dữ liệu dựa trên CategoryId được gửi từ form
                employee.categories = await _context.categories.FindAsync(employee.categoryId);

                // Kiểm tra xem người dùng đã chọn hình ảnh chưa
                if (image != null && image.Length > 0)
                {
                    // Lưu hình ảnh và nhận đường dẫn
                    employee.ImageUrl = await SaveImage(image);
                }

                _context.employees.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            else
            {
                // Nếu có lỗi, trả về lại view "Add" với model chứa thông tin đã được nhập vào
                var positions = await _context.positions.ToListAsync();
                var positionItems = positions.Select(p => new SelectListItem
                {
                    Value = p.positionId.ToString(),
                    Text = p.positionName
                }).ToList();
                ViewBag.Positions = positionItems;

                var categories = await _context.categories.ToListAsync();
                var categoryItems = categories.Select(c => new SelectListItem
                {
                    Value = c.categoryId.ToString(),
                    Text = c.name
                }).ToList();
                ViewBag.Categories = categoryItems;
                // Thêm các thông báo lỗi vào ModelState để hiển thị cho người dùng

                return View(employee);
            }
        }

        public async Task<IActionResult> Update(int id)
        {
            var employee = await _context.employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }

            //Hiển listPosition
            var positions = await _context.positions.ToListAsync();
            var positionItems = positions.Select(p => new SelectListItem
            {
                Value = p.positionId.ToString(),
                Text = p.positionName
            }).ToList();

            ViewBag.Positions = positionItems;

            //Hiển listCategory
            var categories = await _context.categories.ToListAsync();
            var categoryItems = categories.Select(c => new SelectListItem
            {
                Value = c.categoryId.ToString(),
                Text = c.name
            }).ToList();

            ViewBag.Categories = categoryItems;

            return View(employee);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, Employee employee, IFormFile image)
        {
            // Kiểm tra xem id của nhân viên có tồn tại trong cơ sở dữ liệu không
            if (id != employee.employeeId)
            {
                return NotFound();
            }

            // Kiểm tra tính hợp lệ của dữ liệu đầu vào
            if (employee.Address != null)
            {
                try
                {
                    // Lấy nhân viên từ cơ sở dữ liệu
                    var existingEmployee = await _context.employees.FindAsync(id);

                    if (existingEmployee == null)
                    {
                        return NotFound();
                    }

                    // Cập nhật thông tin của nhân viên
                    existingEmployee.FullName = employee.FullName;
                    existingEmployee.DateOfBirth = employee.DateOfBirth;
                    existingEmployee.PhoneNumber = employee.PhoneNumber;
                    existingEmployee.Email = employee.Email;
                    existingEmployee.Address = employee.Address;
                    existingEmployee.Expertise = employee.Expertise;
                    existingEmployee.positionId = employee.positionId;
                    existingEmployee.categoryId = employee.categoryId;

                    // Kiểm tra và cập nhật hình ảnh nếu có
                    if (image != null && image.Length > 0)
                    {
                        // Lưu hình ảnh mới và cập nhật đường dẫn
                        existingEmployee.ImageUrl = await SaveImage(image);
                    }

                    // Cập nhật thông tin của nhân viên trong cơ sở dữ liệu
                    _context.Update(existingEmployee);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    // Xử lý khi xảy ra lỗi cập nhật
                    return NotFound();
                }
            }

            // Nếu dữ liệu không hợp lệ, hiển thị lại form cập nhật với thông tin đã nhập và thông báo lỗi
            var positions = await _context.positions.ToListAsync();
            var positionItems = positions.Select(p => new SelectListItem
            {
                Value = p.positionId.ToString(),
                Text = p.positionName
            }).ToList();
            ViewBag.Positions = positionItems;

            var categories = await _context.categories.ToListAsync();
            var categoryItems = categories.Select(c => new SelectListItem
            {
                Value = c.categoryId.ToString(),
                Text = c.name
            }).ToList();
            ViewBag.Categories = categoryItems;

            return View(employee);
        }


        // Action để xóa một luật sư
        public async Task<IActionResult> Delete(int id)
        {
            var employee = await _context.employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }

            try
            {
                _context.employees.Remove(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", $"Error deleting employee: {ex.Message}");
                return View(employee);
            }
        }

        public async Task<IActionResult> SearchEmployees(string searchTerm)
        {
            var employees = await _context.employees
                .Where(e => e.FullName.Contains(searchTerm) ||
                            e.PhoneNumber.Contains(searchTerm) ||
                            e.Email.Contains(searchTerm) ||
                            e.Address.Contains(searchTerm) ||
                            e.Expertise.Contains(searchTerm) ||
                            e.academicQualification.Contains(searchTerm))
                .ToListAsync();

            return View(employees);
        }

        // Action để tải xuống tất cả thông tin của một luật sư dưới dạng PDF
        public async Task<IActionResult> DownloadAllInfo(int id)
        {
            var lawyer = await _context.employees
                .Include(l => l.positions)

DoAnWeb/Views/Lawyer/Add.cshtml
@model DoAnWeb.Models.Employee
@* @section CustomStyles {
    <link rel="stylesheet" href="~/css/header1.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

} *@
@{
    ViewData["Title"] = "Add Lawyer";
    Layout = "/Views/Admin/_LayoutAdmin.cshtml";
}
<style>
    .container {
        width: 80%;
        border: 1px solid black;
        border-radius: 20px;
        padding: 1.5rem;
        box-shadow: 0 0 10px rgba(0, 10, 0, 0.1);
        margin-left: auto;
        margin-right: auto;
    }

    .card {
        width: 80%;
        margin: auto;
    }
</style>
<div class="container">
    <div class="card">
        <div class="card-header text-center py-4">
            <h2 class="mb-0">Add Lawyer</h2>
        </div>
        <div class="card-body">
            <form asp-action="Add" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="fullName">Full Name:</label>
                    <input type="text" id="fullName" name="fullName" class="form-control" required maxlength="50">
                </div>
                <div class="form-group">
                    <label for="dateOfBirth">Date of Birth:</label>
                    <input type="date" id="dateOfBirth" name="dateOfBirth" class="form-control">
                </div>
                <div class="form-group">
                    <label for="phoneNumber">Phone Number:</label>
                    <input type="tel" id="phoneNumber" name="phoneNumber" class="form-control" required maxlength="10">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" class="form-control" required maxlength="50">
                </div>
                <div class="form-group">
                    <label for="address">Address:</label>
                    <input type="text" id="address" name="address" class="form-control">
                </div>
                <div class="form-group">
                    <label for="expertise">Expertise:</label>
                    <input type="text" id="expertise" name="expertise" class="form-control" required maxlength="50">
                </div>
                <div class="form-group">
                    <label for="position">Position:</label>
                    <select asp-for="positionId" asp-items="@ViewBag.Positions" class="form-control"></select>
                </div>
                <div class="form-group">
                    <label for="category">Category:</label>
                    <select asp-for="categoryId" asp-items="@ViewBag.categories" class="form-control"></select>
                </div>
                <div class="form-group">
                    <div class="form-group mb-4">
                        <label for="imageInput" class="form-label">Image</label>
                        <input type="file" id="imageInput" name="image" class="form-control">
                    </div>
                    <!-- Image Preview -->
                    <img id="imagePreview" src="#" alt="Image Preview" style="width:200px; height:200px;">
                </div>
                <div class="form-group">
                    <label for="commencementDate">Commencement Date:</label>
                    <input type="date" id="commencementDate" name="commencementDate" class="form-control">
                </div>
                <div class="form-group">
                    <label for="academicQualification">Academic Qualification:</label>
                    <input type="text" id="academicQualification" name="academicQualification" class="form-control" required maxlength="50">
                </div>
                <div class="form-group">
                    <label for="facebookURL">Facebook URL:</label>
                    <input type="url" id="facebookURL" name="facebookURL" class="form-control">
                </div>
                <div class="form-group">
                    <label for="instagramURL">Instagram URL:</label>
                    <input type="url" id="instagramURL" name="instagramURL" class="form-control">
                </div>
                <div class="form-group">
                    <label for="twitterURL">Twitter URL:</label>
                    <input type="url" id="twitterURL" name="twitterURL" class="form-control">
                </div>
                <div class="text-center mt-4">
                    <button type="submit" class="btn btn-primary btn-lg px-5" style="width: 200px;">Add</button>
                </div>
            </form>
        </div>
    </div>
</div>



<script>
    document.getElementById('imageInput').addEventListener('change', function () {
        var file = this.files[0];
        var reader = new FileReader();

        reader.onload = function (e) {
            document.getElementById('imagePreview').src = e.target.result;
        };

        reader.readAsDataURL(file);
    });
</script>

DoAnWeb/Views/Lawyer/Index.cshtml
@model List<Employee>
@section CustomStyles {
    @* <link href="~/css/LawyerAdmin.css" rel="stylesheet" /> *@
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
}

@{
    Layout = "~/Views/Admin/_LayoutAdmin.cshtml";
}
<style>
    .container {
        border-radius: 20px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        padding: 20px;
        margin-top: 20px;
        background-color: #f9f9f9;
    }

    .src {
        position: relative;
        left: 200px;
        height: 40px;
        width: 350px;
        margin: 0 0 20px 0;
    }

        .src input {
            position: absolute;
            left: 0;
            top: 0;
            height: 100%;
            width: calc(100% - 50px);
            outline: none;
            border: none;
            background: #f8f3;
            padding-left: 50px;
            font-size: 15px;
            color: #000000;
            border-radius: 20px;
            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
            transition: all 0.5s ease;
        }

        .src .bx {
            line-height: 1.8;
        }


        .src i {
            height: 50px;
            min-width: 50px;
            text-align: center;
            border-radius: 12px;
            font-size: 25px;
        }

    .add-button {
        background-color: #007bff;
        display: flex;
        align-items: center;
        justify-content: center;
        width: 150px;
        height: 40px;
        color: #fff;
        border: none;
        border-radius: 10px;
        padding: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

        .add-button:hover {
            background-color: #0056b3;
        }

    .table-responsive {
        overflow-x: auto;
    }

    th {
        background-color: #007bff;
        color: #fff;
        font-weight: bold;
        padding: 10px;
        text-align: left;
    }

    td {
        border: 1px solid #dee2e6;
        padding: 10px;
    }

    .table {
        width: 100%;
        border-collapse: collapse;
        border-spacing: 0;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 10px;
    }

    .btn-group{
        display:flex;
        gap:20px;
    }
</style>
<div class="container">
    <div class="our-team">
        <h2 class="text-center">Thông tin nhân viên</h2>
        <div class="row mb-3">
            <div class="col-md-6">
                <a asp-action="Add" asp-controller="Lawyer" asp-route-id="lawyer.EmployeeId" class="add-button">Thêm luật sư</a>
            </div>
            <div class="col-md-6">
                <form id="searchForm" class="src">
                    @* <label for="searchTerm">Tìm kiếm:</label> *@
                    <i class="bx bx-search-alt-2"></i>
                    <input type="text" id="searchTerm" placeholder="Nhập từ khóa...">
                </form>
            </div>
        </div>
        <div class="table-responsive lawyers-container">
            @if (Model != null && Model.Any())
            {
                <table id="lawyersTable" class="table table-striped table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th>Họ và Tên</th>
                            <th>Chuyên môn</th>
                            <th>Số điện thoại</th>
                            <th>Email</th>
                            <th>Địa chỉ</th>
                            <th>Ảnh</th>
                            <th>Ngày bắt đầu</th>
                            <th>Bằng cấp</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var lawyer in Model)
                        {
                            <tr>
                                <td>@lawyer.FullName</td>
                                <td>@lawyer.Expertise</td>
                                <td><a href="tel:@lawyer.PhoneNumber">@lawyer.PhoneNumber</a></td>
                                <td><a href="mailto:@lawyer.Email">@lawyer.Email</a></td>
                                <td>@lawyer.Address</td>
                                <td><img src="@lawyer.ImageUrl" alt="Ảnh luật sư" class="img-fluid rounded-circle" style="width: 50px; height: 50px;" /></td>
                                <td>@lawyer.commencementDate</td>
                                <td>@lawyer.academicQualification</td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <form class="d-flex" asp-action="Update" asp-controller="Lawyer" asp-route-id="@lawyer.employeeId" method="get"> 
                                            <button type="submit" class="btn btn-primary btn-sm me-1">Cập nhật</button>
                                        </form>
                                        <form class="d-flex" asp-action="Delete" asp-controller="Lawyer" method="post" onsubmit="return confirm('Bạn có chắc chắn muốn xóa nhân viên này không?');">
                                            <input type="hidden" name="id" value="@lawyer.employeeId" />
                                            <button type="submit" class="btn btn-danger btn-sm">Xóa</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <p class="no-lawyers">Không tìm thấy luật sư.</p>
            }
        </div>
    </div>
</div>

@section scripts {

    <script>
        function searchTable() {
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("searchTerm");
            filter = input.value.toUpperCase();
            table = document.getElementById("lawyersTable");
            tr = table.getElementsByTagName("tr");

            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td");
                for (var j = 0; j < td.length; j++) {
                    if (td[j]) {
                        txtValue = td[j].textContent || td[j].innerText;
                        if (txtValue.toUpperCase().indexOf(filter) > -1) {
                            tr[i].style.display = "";
                            break; // Nếu tìm thấy, hiển thị dòng và thoát khỏi vòng lặp
                        } else {
                            tr[i].style.display = "none"; // Nếu không tìm thấy, ẩn dòng
                        }
                    }
                }
            }
        }

        // Lắng nghe sự kiện khi người dùng nhập vào ô tìm kiếm
        document.getElementById("searchTerm").addEventListener("keyup", function () {
            searchTable();
        });
    </script>
}

DoAnWeb/Views/Lawyer/Update.cshtml
@model DoAnWeb.Models.Employee
 @section CustomStyles {
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link href="~/css/bootstrap.css" rel="stylesheet" />
} 
@{
    ViewData["Title"] = "Edit Lawyer";
    Layout = "/Views/Admin/_LayoutAdmin.cshtml";

}
<style>
    .container {
        width: 80%;
        border: 1px solid black;
        border-radius: 20px;
        padding: 1.5rem;
        box-shadow: 0 0 10px rgba(0, 10, 0, 0.1);
        margin-left: auto;
        margin-right: auto;
    }

    .card {
        width: 80%;
        margin: auto;
    }

</style>
<div class="container">
    <div class="card ">
        <div class="card-header">
            <h3 class="text-center font-weight-light my-4">Edit Lawyer</h3>
        </div>
        <div class="card-body">
            <form asp-action="Update" method="post" enctype="multipart/form-data">
                <input type="hidden" asp-for="employeeId" />

                <div class="row mb-3">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="fullName" class="form-label">Full Name</label>
                            <input type="text" id="fullName" asp-for="FullName" class="form-control" required maxlength="50">
                            <span asp-validation-for="FullName" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="dateOfBirth" class="form-label">Date of Birth</label>
                            <input type="date" id="dateOfBirth" asp-for="DateOfBirth" class="form-control">
                            <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="phoneNumber" class="form-label">Phone Number</label>
                            <input type="tel" id="phoneNumber" asp-for="PhoneNumber" class="form-control" required maxlength="10">
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" id="email" asp-for="Email" class="form-control" required maxlength="50">
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label for="address" class="form-label">Address</label>
                            <input type="text" id="address" asp-for="Address" class="form-control">
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="expertise" class="form-label">Expertise</label>
                            <input type="text" id="expertise" asp-for="Expertise" class="form-control" required maxlength="50">
                            <span asp-validation-for="Expertise" class="text-danger"></span>
                        </div>

                    </div>

                    <div class="col-md-6">

                        <div class="form-group">
                            <label for="positionId" class="form-label">Position</label>
                            <select id="positionId" asp-for="positionId" asp-items="@ViewBag.Positions" class="form-select">
                                <option value="">Select Position</option>
                            </select>
                            <span asp-validation-for="positionId" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="categoryId" class="form-label">Category</label>
                            <select id="categoryId" asp-for="categoryId" asp-items="@ViewBag.Categories" class="form-select">
                                <option value="">Select Category</option>
                            </select>
                            <span asp-validation-for="categoryId" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <label for="commencementDate" class="form-label">Commencement Date</label>
                            <input type="date" id="commencementDate" asp-for="commencementDate" name="commencementDate" class="form-control">
                            <span asp-validation-for="commencementDate" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label for="facebookURL" class="form-label">Facebook URL</label>
                            <input type="url" id="facebookURL" name="facebookURL" class="form-control" value="@Model.facebookURL">
                        </div>

                        <div class="form-group">
                            <label for="instagramURL" class="form-label">Instagram URL</label>
                            <input type="url" id="instagramURL" name="instagramURL" class="form-control" value="@Model.instagramURL">
                        </div>

                        <div class="form-group">
                            <label for="twitterURL" class="form-label">Twitter URL</label>
                            <input type="url" id="twitterURL" name="twitterURL" class="form-control" value="@Model.twitterURL">
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="imageInput" class="form-label">Image</label>
                            <input type="file" id="imageInput" name="image" class="form-control">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="imagePreview" class="form-label">Image Preview</label><br>
                            <img id="imagePreview" src="@Model.ImageUrl" alt="Image Preview" style="width:200px;height:200px">
                        </div>
                    </div>
                </div>

                <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary btn-lg me-2">Save</button>
                    
                </div>
            </form>
        </div>
    </div>

</div>

<script>
    document.getElementById('imageInput').addEventListener('change', function () {
        var file = this.files[0];
        var reader = new FileReader();

        reader.onload = function (e) {
            document.getElementById('imagePreview').src = e.target.result;
            document.getElementById('imagePreview').style.display = 'block';
        };

        if (file) {
            reader.readAsDataURL(file);
        } else {
            // Nếu không có tệp được chọn, hiển thị hình ảnh hiện tại của nhân viên
            document.getElementById('imagePreview').src = '@Model.ImageUrl';
            document.getElementById('imagePreview').style.display = 'block';
        }
    });
</script>